#!/bin/bash

# Copyright (c) 2008-2010 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
# Author: Eric Woodruff <eric dot woodruff at gmail.com>

# This file is meant to be linked from /etc/bash_completion.d/rmake

_rmake ()
{
	local rmakeorig="$(readlink -e $(which rmake))"
	local rmake="${rmakeorig%/*}/rmake"

	if [ ! -f ${rmake} ]; then
		rmake=${rmakeorig}
	fi
	
	COMPREPLY=()
	local cur=${COMP_WORDS[COMP_CWORD]}
	local prev=${COMP_WORDS[COMP_CWORD-1]}
	
	case $prev in
	-@(C|-directory))
		complete -F _rmake -o filenames -o nospace rmake
		_cd
		return $?
		;;
	-@(L|-log-dir))
		complete -F _rmake -o filenames -o nospace rmake
		_filedir -d
		return $?
		;;
	-@(F|-file-list))
		complete -F _rmake -o filenames -o nospace rmake
		local root=$(${rmake} -w 2>/dev/null) || return 1
		if [ ! -d "${root}" ]; then
			return 1
		fi
		pushd "${root}" >/dev/null 2>&1
		_filedir
		local i
		for (( i=0; i < ${#COMPREPLY[@]}; i++ )); do
		    [ -d ${COMPREPLY[i]} ] && COMPREPLY[i]="${COMPREPLY[i]}/"
		done
		popd >/dev/null 2>&1
		return 0
		;;
	-x|--exec)
		complete -F _rmake -o bashdefault rmake
		COMPREPLY=( $( compgen -c -a -A function -- $cur ) )
		return $?
		;;
	-p|--platform)
		complete -F _rmake -o filenames rmake
		COMPREPLY=( $(compgen -W "$( ${rmake} -l )" -- ${cur} ) )
		return 0
		;;
	esac

	complete -F _rmake -o bashdefault rmake
	if [[ "$cur" == -* ]]; then
		COMPREPLY=( $(compgen -W "$(${rmake} -h | awk '{print substr($0,1,28)}' | grep -Eo -- ' --?[a-zA-Z_-]{1,}' | sort -u)" -- ${cur} ) )
	else
		_make
	fi

	return 0
}

complete -F _rmake rmake
