#! /bin/bash

# Copyright (c) 2012 Eric Woodruff
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
# Author: Eric Woodruff <eric dot woodruff at gmail.com>


function svn-name () {
	echo "git"
}

function rsync-option-svn-meta-exclude-all () {
	echo "--exclude=\".git/\""
}

function rsync-option-svn-meta-exclude-base () {
	# TODO validate this!
	echo "--exclude=\".git/objects/\""
}

function svn-dirty-command () {
	echo "git ls-files --other --exclude-standard"
}

function svn-excludes-file () {
	local options=""
	if [ -n "${svnbase}" ]; then
		options="A"
	fi
	# All excludes files must be relative (starting with /) from LOCAL_WORKSPACE_ROOT
	git diff --no-renames --name-only --diff-filter=${options}CDMRTUXB HEAD | \
		sed -e "s%${LOCAL_WORKSPACE_ROOT}/\(.*\)%/\1%" > ${excludesfile}
}

function svn-base-tar-create () {
	local tarfile=$TMPDIR/rmake.tar.$$
	git ls-files --deleted --unmerged --modified --full-name | sort > ${tarfile}
	git stash --no-keep-index
	tar --directory "${LOCAL_WORKSPACE_ROOT}" -czf "${basefile}" --files-from=${tarfile} \
		--mode="a-w+x"
	git stash pop --index
	rm ${tarfile}
}
