#! /bin/bash

# Copyright (c) 2008-2010 Hewlett-Packard Development Company, L.P.
# Copyright (c) 2012 Eric Woodruff
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
# Author: Eric Woodruff <eric dot woodruff at gmail.com>

function svn-name () {
	echo "svn"
}

function rsync-option-svn-meta-exclude-all () {
	echo "--exclude=\".svn/\""
}

# $1: original file
function svn-pristine-file () {
	sqlite3 ${LOCAL_WORKSPACE_ROOT}/.svn/wc.db \
	"select \"${LOCAL_WORKSPACE_ROOT}/.svn/pristine/\" || substr(checksum,7,2) || \"/\" || substr(checksum,7) || \".svn-base\" as alpha from NODES where local_relpath=\"$1\";"
}

function cleanup-pristine-links () {
	rm -rf "${LOCAL_WORKSPACE_ROOT}/.svn/rmake/svn-base/"
}

function make-pristine-links () {
	cleanup-pristine-links
	rm -rf "${LOCAL_WORKSPACE_ROOT}/.svn/rmake/svn-base/"
	set -x
	while read f; do
		local pristine=$(svn-pristine-file "$f")
		local base=".svn/rmake/svn-base/$f"
		local basedir="${base%/*}"

		mkdir -p "${LOCAL_WORKSPACE_ROOT}/$basedir"
		ln "$pristine" "${LOCAL_WORKSPACE_ROOT}/$base"
		echo "$base"
	done
}

function rsync-option-svn-meta-exclude-base () {
	echo "--exclude=\".svn/pristine/\""
}

function svn-dirty-command () {
	echo "svn status --no-ignore | grep \"^?\"'"
}

function svn-excludes-file () {
	excludesxsl="${RMAKE_LIB}/svnexcludes.xsl"
	if [ -n "${svnbase}" ]; then
		excludesxsl="${RMAKE_LIB}/svnbase_excludes.xsl"
	fi

	# All excludes files must be relative (starting with /) from LOCAL_WORKSPACE_ROOT
	svn status --no-ignore --xml -v "${excluderoot}" | \
		xsltproc "${excludesxsl}" - | \
		sed -e "s%${LOCAL_WORKSPACE_ROOT}/\(.*\)%/\1%" > ${excludesfile}
}

function svn-base-tar-create () {
	# recreate compatible svn-base symlinks
	svn status --no-ignore --xml -v "${baseroot}" | \
		xsltproc "${RMAKE_LIB}/svnbase_changes.xsl" - | \
		sort | \
		sed -e ':read; N; s/^\(.*\)\n\(\1\/.\+\)$/\2/; t read; P; s/^\(.*\)\n//; b read' | \
		sed -e "s%^${LOCAL_WORKSPACE_ROOT}/\(.*\)%\1%" | \
		make-pristine-links |
		tar --directory "${LOCAL_WORKSPACE_ROOT}" -czf "${basefile}" --files-from=- \
			--transform="s%.svn/rmake/svn-base/\(.*\)%\1%" \
			--mode="a-w+x"
	cleanup-pristine-links
}
